---
## mirai-api-http 的链接
host: "localhost"
## mirai-api-http 的端口
port: 8080
## bot 登录账号
account: 123456789
## mirai-api-http 的验证码
verify_key: "INITKEYWylsVdbr"
## bot 的控制者的账号
master_id: 987654321
## bot 的控制者的名字
master_name: "admin"
## 机器人名字, 用于对话; 请尽量不要与 prefix 重合
bot_name: "Raian"
## 命令前缀; At:123456 会转换为 At(123456), Face:xxx 会转换为 Face(name=xxx)
prefix:
  - "莱安"
  - "At:123456789"
## 插件需要的数据
plugin:
  ## 信赖最大值
  sign_max: 200
  ## 请自行前往 https://saucenao.com 中获取
  saucenao: 'xxxxxxxxxxxxxxxxxxxxxx'
  ## 卡池的文件路径
  gacha: "assets/data/gacha_arknights.json"
  ## stable-diffusion-webui-api的接口地址
  txt2img: "xxxxxxxxxxx"
  ## ai 对话
  dialog:
    ## 触发词
    nickname: "莱安"
    ## 是否使用腾讯云翻译, 是则需要填写腾讯云接口的secret-id secret-key
    tencent: true
    id: "xxxxxxxxxxxxxxxxxxxx"
    key: "xxxxxxxxxxxxxxxxxxx"
    ai_url: ""
## 插件的父级路径
plugin_path: plugins
## 禁用的功能列表
disabled_plugins: ['setu', 'ill', 'img_search']

## 群组的附加元数据, 为插件提供数据字段
group_meta:
  - mute
  - weibo_followers
  - roles
## 用户的附加元数据, 为用户功能提供数据字段
user_meta:
  - gacha_proba
  - draw_info
  - sign_info
## 缓存数据存放的文件夹, 默认为 cache
cache_dir: 'cache'
...