---
## mirai-api-http 的链接
host: "localhost"
## mirai-api-http 的端口
port: 8080
## bot 登录账号
account: 123456789
## mirai-api-http 的验证码
verify_key: "INITKEYWylsVdbr"
## bot 的控制者的账号
master_id: 987654321
## bot 的控制者的名字
master_name: "admin"
## 命令前缀; At:123456 会转换为 At(123456), Face:xxx 会转换为 Face(name=xxx)
prefix:
  - "莱安"
  - "At:3542928737"
api:
  ## 请自行前往 https://saucenao.com 中获取
  saucenao: 'xxxxxxxxxxxxxxxxxxxxxx'
## 插件的父级路径
plugin_path: plugins
## 禁用的功能列表
disabled_plugins: []
## 群组的附加元数据, 为插件提供数据字段
group_meta:
  - weibo_followers
## 用户的附加元数据, 为用户功能提供数据字段
user_meta:
  - gacha_proba
  - draw_info
...