[project]
name = "raian-bot"
version = "0.9.0"
description = "simple qq bot bases on Araidne and Alconna"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"},
]
dependencies = [
    "arclet-alconna<2.0.0, >=1.2.0.1",
    "arclet-alconna-graia<1.0.0, >=0.4.7",
    "graia-ariadne>=0.7.15",
    "graia-broadcast>=0.18.1",
    "graia-saya~=0.0.16",
    "graia-scheduler~=0.0.8",
    "unwind~=0.3.1",
    "Pillow>=9.0.1",
    "aiohttp~=3.8.1",
    "pyquery~=1.4.3",
    "pydantic~=1.9.0",
    "picimagesearch~=3.3.2",
    "playwright~=1.14.1",
    "PyYAML~=6.0",
    "loguru~=0.6.0",
    "psutil~=5.9.0",
    "tencentcloud-sdk-python==3.0.495",
    "ujson~=5.1.0",
    "creart~=0.2.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "AGPL-3.0"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"


[tool]
[tool.pdm]
