name: 功能建议
title: "[Feature]: "
description: 提出关于项目新功能的想法
labels: ["enhancement"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 确认项
      description: 请确认以下选项
      options:
        - label: 新特性的目的明确
          required: true
        - label: 我已经使用过该项目并且了解其功能
          required: true
  - type: textarea
    id: problem
    attributes:
      label: 希望能解决的问题
      description: 在使用中遇到什么问题而需要新的功能？
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: 描述所需要的功能
      description: 请说明需要的功能或解决方法
    validations:
      required: true
