## 允许的最多禁言恢复剩余次数
mute_max: 5
## 是否启用公告广播功能
enable_announcement: true
## 公告的标题
announcement_title: "来自管理者的公告"
## 是否启用闪照截取功能
enable_fetch_flash: true
## 是否启用机器人启动后事件
enable_start_report: true
## 是否启动后进行检查
check_group_in_start: true
## 是否启用户相关事件
enable_member_report: true
## 用户入群时的欢迎词
member_join_welcome: null
## 是否启用好友或入群申请处理
enable_request_handle: true
